routes.py
from flask import flash, render_template, request, url_for, redirect, Blueprint
from sqlalchemy import func
from extensions import db
from models import Product, Recipe, GroceryList


main = Blueprint("main", __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/products')
def products():
    table = Product.query.all()
    return render_template('products.html', products=table)


@main.route('/products/update/<int:product_id>', methods=['POST'])
def update_product(product_id):
    product = db.get_or_404(Product, product_id)

    if request.form.get('delete_product'):
        db.session.delete(product)
        db.session.commit()
        flash(f'Deleted: {product.name}')
        return redirect(url_for('main.products'))

    product.name = request.form.get('name')
    product.brand = request.form.get('brand')
    product.store = request.form.get('store')
    product.category = request.form.get('category')
    gluten = request.form.get('gluten')
    if gluten == '':
        product.gluten = False
    else:
        product.gluten = eval(gluten.capitalize())
    product.price = eval(request.form.get('price'))
    product.updated = func.now()
    db.session.commit()
    flash(f'Updated: {product.name}')
    return redirect(url_for('main.products'))


@main.route('/products/add', methods=['POST'])
def add_product():
    product = Product()
    product.name = request.form.get('name')
    product.brand = request.form.get('brand')
    product.store = request.form.get('store')
    product.category = request.form.get('category')
    gluten = request.form.get('gluten')
    if gluten == '':
        product.gluten = False
    else:
        product.gluten = eval(gluten.capitalize())
    price = request.form.get('price')
    if price == '':
        product.price = 0.0
    else:
        product.price = eval(request.form.get('price'))
    db.session.add(product)
    db.session.commit()
    flash(f'Added: {product.name}')
    return redirect(url_for('main.products'))


@main.route('/grocery_list')
def grocery_list():
    table = GroceryList.query.all()
    total = 0.0
    for row in table:
        total += row.subtotal
    products_with_quantities = {}
    for row in table:
        product = db.get_or_404(Product, row.product_id)
        products_with_quantities[product.name] = {
            'id': product.id, 'quantity': row.quantity, 'store': product.store, 'price': product.price,
            'subtotal': row.subtotal,
        }
    return render_template('grocery_list.html',
                           products_with_quantities=products_with_quantities, total=total)


@main.route('/grocery_list/update/quantity/<int:product_id>', methods=['POST'])
def update_grocery_list_quantity(product_id):
    product = db.get_or_404(Product, product_id)
    table = db.session.query(GroceryList).filter(GroceryList.product_id == product_id).all()

    decrease = request.form.get('decrease')
    increase = request.form.get('increase')
    for row in table:
        if decrease and row.quantity > 1:
            row.quantity -= 1
        elif increase:
            row.quantity += 1
        row.subtotal = product.price * row.quantity
        db.session.commit()

    return redirect(url_for('main.grocery_list'))


@main.route('/grocery_list/remove/product', methods=['POST'])
def remove_product_from_grocery_list():
    product_id = request.form.get('product_id')
    product = db.get_or_404(Product, product_id)
    table = db.session.query(GroceryList).filter(GroceryList.product_id == product_id).all()
    product.in_list = False
    for row in table:
        db.session.delete(row)
        db.session.commit()
    return redirect(url_for('main.grocery_list'))


@main.route('/grocery_list/add/product/<int:product_id>', methods=['POST'])
def add_product_to_grocery_list(product_id, quantity=None):
    product = db.get_or_404(Product, product_id)

    # check if the product is in the grocery list table
    result = db.session.query(GroceryList).filter(GroceryList.product_id == product_id).all()
    if any(result):
        # product is in the table so it should be removed
        product.in_list = False
        for row in result:
            db.session.delete(row)
            db.session.commit()

    else:
        # add a product to the grocery list table
        product.in_list = True
        grocery_item = GroceryList()
        grocery_item.product_id = product_id
        grocery_item.quantity = quantity if quantity else 1
        grocery_item.subtotal = product.price
        db.session.add(grocery_item)
        db.session.commit()
    return redirect(url_for('main.products'))


@main.route('/grocery_list/add/recipe/<int:recipe_id>', methods=['POST'])
def add_recipe_to_grocery_list(recipe_id):
    recipe = db.get_or_404(Recipe, recipe_id)
    products_quantities = eval(recipe.products)
    products_added = []
    for product_id, quantity in products_quantities.items():
        if quantity == '0':
            continue
        result = db.session.query(GroceryList).filter(GroceryList.product_id == product_id).all()
        if any(result):
            for row in result:
                if row.product_id == int(product_id):
                    product_price = db.get_or_404(Product, int(product_id)).price
                    row.quantity += int(quantity)
                    row.subtotal = row.quantity * product_price
                    db.session.commit()
                    product = db.get_or_404(Product, int(product_id))
                    products_added.append(product.name)

        else:
            product = db.get_or_404(Product, int(product_id))
            product.in_list = True
            grocery_item = GroceryList()
            grocery_item.product_id = product_id
            grocery_item.quantity = quantity if quantity else 1
            grocery_item.subtotal = product.price
            db.session.add(grocery_item)
            products_added.append(product.name)
    db.session.commit()

    flash(f'Added products to grocery list: {products_added}')
    return redirect(url_for('main.recipes'))


@main.route('/recipes')
def recipes():
    table_recipe = Recipe.query.all()
    table_product = Product.query.all()
    return render_template('recipes.html', recipes=table_recipe, products=table_product)


@main.route('/recipes/add', methods=['POST'])
def add_recipe():
    recipe = Recipe()
    recipe.name = request.form.get('name')
    recipe.description = request.form.get('description')
    quantity_ids = [quantity_id for quantity_id in request.form.keys() if 'quantity' in quantity_id]
    products = {}
    for quantity_id in quantity_ids:
        quantity = request.form.get(quantity_id)
        if quantity != '0':
            products[quantity_id.split('_')[1]] = request.form.get(quantity_id)
    recipe.products = str(products)
    db.session.add(recipe)
    db.session.commit()
    flash(f'Added: {recipe.name}')
    return redirect(url_for('main.recipes'))


@main.route('/recipes/update/<int:recipe_id>', methods=['POST'])
def update_recipe(recipe_id):
    recipe = db.get_or_404(Recipe, recipe_id)
    if request.form.get('delete_recipe'):
        db.session.delete(recipe)
        db.session.commit()
        flash(f'Deleted: {recipe.name}')
        return redirect(url_for('main.recipes'))

    recipe.name = request.form.get('recipe_name')
    recipe.description = request.form.get('recipe_description')
    quantity_ids = [quantity_id for quantity_id in request.form.keys() if 'quantity' in quantity_id]
    products = {}
    for quantity_id in quantity_ids:
        products[quantity_id.split('_')[1]] = request.form.get(quantity_id)
    recipe.products = str(products)
    db.session.add(recipe)
    db.session.commit()
    flash(f'Updated: {recipe.name}')
    return redirect(url_for('main.recipes'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        <i class="bi bi-shop"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/products"><i class="bi bi-card-list"></i> products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recipes"><i class="bi bi-postcard-heart"></i> recipes</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="/grocery_list"><i class="bi bi-cart3"></i> grocery list</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</div>
</body>
</html>

templates/grocery_list.html
{% extends "base.html" %}

{% block title %}
  {{ url_for('main.grocery_list') }}
{% endblock %}


{% block content %}

<table class="table">

  <th></th>
  <th>Name</th>
  <th>Store</th>
  <th>Quantity</th>
  <th>Price</th>
  <th>Subtotal</th>

    {% for product_name, product_data in products_with_quantities.items() %}
        <tr>
          <td>
            <form action="{{ url_for('main.remove_product_from_grocery_list')}}" method="POST">
              <button class="btn btn-danger btn-sm" type="submit" name="product_id" value="{{ product_data['id'] }}">-</button>
            </form>
          </td>
          <td>{{ product_name }}</td>

          <td>{{ product_data['store'] }}</td>

          <td>
            <form action="{{ url_for('main.update_grocery_list_quantity', product_id=product_data['id']) }}" method="POST">
              <div class="input-group input-group-sm" style="width: 50%">

                <button class="btn btn-outline-danger" name="decrease" value="-1">-</button>
                <input type="text" readonly style="text-align: center" class="form-control input-number" id="floatingInput"  value="{{ product_data['quantity'] }}">
                <button class="btn btn-outline-success" name="increase" value="+1">+</button>

              </div>
            </form>
          </td>

          <td>{{ product_data['price'] }}</td>
          <td>{{ product_data['subtotal'] }}</td>

        </tr>
    {% endfor %}
</table>

<nav class="navbar fixed-bottom bg-body-tertiary ">
  <div class="container-fluid">
    <a class="navbar-brand position-absolute bottom-0 end-0" href="#">Total amount:  <i class="bi bi-currency-euro"></i>{{ total }}</a>
  </div>
</nav>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
  {{ url_for('main.index') }}
{% endblock %}


{% block content %}


<br/>
<div class="container-fluid text-center">
  <div class="row">
    <div class="col">
      <form action="{{ url_for('main.products') }}">
        <button type="submit" class="btn btn-outline-success">
          <h1><i class="bi bi-card-list"></i></h1>
          <h5>All products</h5>
        </button>
      </form>
    </div>
    <div class="col">
      <form action="{{ url_for('main.recipes') }}">
        <button type="submit" class="btn btn-outline-success">
          <h1><i class="bi bi-postcard-heart"></i></h1>
          <h5>Recipes</h5>
        </button>
      </form>
    </div>
    <div class="col">
      <form action="{{ url_for('main.grocery_list') }}">
        <button type="submit" class="btn btn-outline-success">
          <h1><i class="bi bi-cart3"></i></h1>
          <h5>Grocery list</h5>
        </button>
      </form>
    </div>
  </div>

{% endblock %}

templates/products.html
{% extends "base.html" %}

{% block title %}
  {{ url_for('main.products') }}
{% endblock %}


{% block content %}


<!-- Button trigger modal for adding a product -->
<button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addProductModal">
  + product
</button>

<!-- Modal popup for adding product information -->
<div class="modal fade" id="addProductModal" tabindex="-1" aria-labelledby="addProductModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <form action="{{ url_for('main.add_product')}}" method="POST">

        <div class="modal-header">
          <h5 class="modal-title" id="addProductModalLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
          <table class="table table-striped-columns">
            <tr><td>Name</td><td><input class="form-control" type="text" name="name" value=""></td></tr>
            <tr><td>Brand</td><td><input class="form-control" type="text" name="brand" value=""></td></tr>
            <tr><td>Store</td><td><input class="form-control" type="text" name="store" value=""></td></tr>
            <tr><td>Category</td><td><input class="form-control" type="text" name="category" value=""></td></tr>
            <tr><td>Gluten</td><td><input class="form-control" type="text" name="gluten" value=""></td></tr>
            <tr><td>Price</td><td><input class="form-control" type="text" name="price" value=""></td></tr>
          </table>
        </div>

        <div class="modal-footer">
          <button type="submit" class="btn btn-primary btn-sm"><i class="bi bi-save-fill"></i></button>
        </div>

      </form>

    </div>
  </div>
</div>




<table class="table table-striped">
  <th>Name</th>
  <th>Store</th>
  <th>Added to grocery list</th>

  {% for product in products %}
    <tr>
      <td>

        <!-- Button trigger modal for updating products -->
        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#productModal{{ product.id }}"><i class="bi bi-info"></i></button>

        <!-- Modal popup for updating product information -->
        <div class="modal fade" id="productModal{{ product.id }}" tabindex="-1" aria-labelledby="productModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">

              <form action="{{ url_for('main.update_product', product_id=product.id)}}" method="POST">

                <div class="modal-header">
                  <h5 class="modal-title" id="productModalLabel">{{ product.name }}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                  <table class="table table-striped-columns">

                    <tr><td>Name</td><td><input class="form-control" type="text" name="name" value="{{ product.name }}"></td></tr>
                    <tr><td>Brand</td><td><input class="form-control" type="text" name="brand" value="{{ product.brand }}"></td></tr>
                    <tr><td>Store</td><td><input class="form-control" type="text" name="store" value="{{ product.store }}"></td></tr>
                    <tr><td>Category</td><td><input class="form-control" type="text" name="category" value="{{ product.category }}"></td></tr>
                    <tr><td>Gluten</td><td><input class="form-control" type="text" name="gluten" value="{{ product.gluten }}"></td></tr>
                    <tr><td>Price</td><td><input class="form-control" type="text" name="price" value="{{ product.price }}"></td></tr>
                    <tr><td>Updated</td><td>{{ product.updated}}</td></tr>

                  </table>
                </div>

                <div class="modal-footer">


                  <button type="submit" class="btn btn-danger btn" value="Delete" name="delete_product"><i class="bi bi-trash-fill"></i></button>
                  <button type="submit" class="btn btn-primary btn"><i class="bi bi-save-fill"></i></button>
                </div>

              </form>

            </div>
          </div>
        </div>
        {{ product.name}}
      </td>
      <td>{{ product.store}}</td>
      <td>
        <form action="{{ url_for('main.add_product_to_grocery_list', product_id=product.id)}}" method="POST">
          <div class="btn-group">
            {% if product.in_list %}
            <button class="btn btn-danger btn-sm" type="submit"">
              <i class="bi bi-plus-slash-minus"></i>
            </button>

            {% else %}
                <button class="btn btn-success btn-sm" type="submit"">
                  <i class="bi bi-plus-slash-minus"></i>
                </button>

            {% endif %}
          </div>
        </form>
      </td>
    </tr>
  {% endfor %}
</table>


{% endblock %}

templates/recipes.html
{% extends "base.html" %}

{% block title %}
  {{ url_for('main.recipes') }}
{% endblock %}


{% block content %}

<!-- Button trigger modal for adding a recipe -->
<button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addRecipeModal">
  + recipe
</button>


<!-- Modal popup for adding recipe information -->
<div class="modal fade" id="addRecipeModal" tabindex="-1" aria-labelledby="addRecipeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="{{ url_for('main.add_recipe')}}" method="POST">

        <div class="modal-header">
          <h5 class="modal-title" id="addRecipeModalLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
          <table class="table table-striped-columns">
            <tr>
                <td>Name</td><td><input class="form-control" type="text" name="name" value=""></td>
            </tr>

            <tr>
              <td>Products</td>

              <td>
                <ul class="list-group">
                  {% for product in products %}
                    <li class="list-group-item">
                        <div class="container text-center">
                          <div class="row">
                            <div class="col">
                              {{ product.name }}
                            </div>
                              <div class="col">
                                <input class="form-control" type="number" name="quantity_{{ product.id }}" value="0" style="width: 50%" min="0">
                              </div>
                          </div>
                        </div>
                    </li>
                  {% endfor %}
                </ul>
              </td>
            </tr>

              <tr>
                  <td>Description</td>
                  <td>
                      <div class="input-group">
                          <textarea class="form-control" name="description" aria-label="With textarea"></textarea>
                      </div>
                  </td>
              </tr>

          </table>
        </div>

        <div class="modal-footer">
          <button type="submit" class="btn btn-primary btn-sm"><i class="bi bi-save-fill"></i></button>
        </div>

      </form>
    </div>
  </div>
</div>


{% for recipe in recipes %}


<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ recipe.name }}</h5>
      <p class="card-text">{{ recipe.description }}</p>


      <!-- Button for recipe information -->
      <div class="btn-group" role="group">
      <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#recipeModal{{ recipe.id }}"><i class="bi bi-info"></i></button>

        <!-- Button to add recipe products to grocery list -->
      <form action="{{ url_for('main.add_recipe_to_grocery_list', recipe_id=recipe.id)}}" method="POST">
        <button class="btn btn-success btn-sm">+ <i class="bi bi-cart3"></i></button>
      </form>
      </div>

      <!-- Modal popup for updating recipe information -->
      <div class="modal fade" id="recipeModal{{ recipe.id }}" tabindex="-1" aria-labelledby="recipeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

            <form action="{{ url_for('main.update_recipe', recipe_id=recipe.id)}}" method="POST">

              <div class="modal-header">
                <h5 class="modal-title" id="recipeModalLabel">{{ recipe.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>

              <div class="modal-body">
                <table class="table table-striped-columns">

                  <tr>
                    <td>Name</td><td><input class="form-control" type="text" name="recipe_name" value="{{ recipe.name }}"></td>
                  </tr>

                  <tr>
                    <td>Products</td>

                    <td>
                      <ul class="list-group">
                        {% for product in products %}
                          <li class="list-group-item">
                            <div class="container text-center">
                              <div class="row">
                                <div class="col">
                                  {{ product.name }}
                                </div>
                                <div class="col">
                                  <input class="form-control" type="number" name="quantity_{{ product.id }}" value="{{ get_product_quantity(recipe.products, product.id) }}" style="width: 50%" min="1">
                                </div>
                              </div>
                            </div>
                          </li>
                        {% endfor %}
                      </ul>
                    </td>
                  </tr>

                  <tr>
                    <td>Description</td>
                    <td>
                        <div class="input-group">
                            <textarea class="form-control" name="recipe_description" aria-label="With textarea">{{ recipe.description }}</textarea>
                        </div>
                    </td>
                  </tr>




                </table>
              </div>

              <div class="modal-footer">

                <button type="submit" class="btn btn-danger btn" value="Delete" name="delete_recipe"><i class="bi bi-trash-fill"></i></button>
                <button type="submit" class="btn btn-primary btn"><i class="bi bi-save-fill"></i></button>
              </div>

            </form>

          </div>
        </div>
      </div>



    </div>

</div>
{% endfor %}
{% endblock %}